### ISSUE TITLE
Fail to get a dict from SoS

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-r#6] opened 2018-05-21 20:01 UTC
Failed to get a `dict()` from `SoS` to `R`:

<img width="865" alt="screen shot 2018-05-21 at 3 01 07 pm" src="https://user-images.githubusercontent.com/26916551/40327249-d4dd87d6-5d07-11e8-8261-7f895da28fa7.png">
<img width="875" alt="screen shot 2018-05-21 at 3 01 15 pm" src="https://user-images.githubusercontent.com/26916551/40327254-d75bae48-5d07-11e8-8338-a380ed6ffc7e.png">

**Comment by HenryLeongStat** [comment] 2018-05-21 20:03
I can upload the `pickle` file for the reproduction of the error...

**Comment by BoPeng** [comment] 2018-05-21 20:32
Yes, raw data and steps to reproduce the bug is needed.

**Comment by HenryLeongStat** [comment] 2018-05-21 20:41
The steps is below:
```
import pickle
import pandas as pd
with open('/Users/manchongleong/Desktop/Crate/Workspaces/Henry/taxnomy/code/L2_mul.pkl', 'rb') as handle:
    c = pickle.load(handle)
unique_whole_data = {}
for key in c:
    #unique_whole_data[key] = b[key].groupby(['profe', 'licen_num']).size().reset_index(name='Freq')
    unique_whole_data[key] = c[key].groupby('profe').size().reset_index(name='Freq')
```
```
%use R
%get unique_whole_data
head(unique_whole_data)
```
[L2_mul.pkl.zip](https://github.com/vatlab/sos-r/files/2024029/L2_mul.pkl.zip)

**Comment by BoPeng** [comment] 2018-05-21 20:52
The problem is with the key of your dictionary, which is translated to something like

```
list(1003001678=..read.feather(
```

**Comment by BoPeng** [comment] 2018-05-21 21:08
So you see that in [this line](https://github.com/vatlab/sos-r/blob/master/src/sos_r/kernel.py#L66) sos does not do anything to the keys of the dictionary and trust that the resulting key is acceptable to R. In reality this can fail for the problem reported here, and for cases such as

```
a = {(1,2): 5}
```
since `R` list only accept string as keys. Now, the easiest solution is something like the `clean` function defined [here](https://stackoverflow.com/questions/3303312/how-do-i-convert-a-string-to-a-valid-variable-name-in-python), although I would prefer adding `x` to `12345` instead of removing leading numbers.

**Comment by BoPeng** [comment] 2018-05-21 21:10
The other solution 

```
>>> clean = lambda varStr: re.sub('\W|^(?=\d)','_', varStr)
```
is even better.

**Comment by HenryLeongStat** [comment] 2018-05-21 21:15
>since R list only accept string as keys. 
But for the dataset here, all of the key is `str`.
Just checked it with:
```
for key in unique_whole_data:
    if not isinstance(key, str):
        print("got it")
```

**Comment by BoPeng** [comment] 2018-05-21 21:19
I know it is string, but when it passes to R, the syntax becomes

```
list(1003001678=..read.feather(
```
which is unacceptable to R.

I am suggesting that you use the aforementioned function to convert the code to

```
list(_1003001678=..read.feather(
```
which alters the key but at least the data is passed.

Note that R accepts

```
list("1003001678"=..read.feather(
```
but using the list in R would be troublesome (you cannot use `data$1003001678`).

The patch would also solves the problem with transferring

```
a = {(1,2): 3}
```
to R because R does not accept non-string as key at all. The patch would transfer it as

```
list(_1_2 = 3)
```
which is not ideal, but at least get most of the data passed.

**Comment by HenryLeongStat** [comment] 2018-05-21 21:21
Oh! I see the problem! Let me fix the `kernel.py`

**Comment by HenryLeongStat** [comment] 2018-05-23 20:11
I am thinking whether we need to check each key first or not.

1. If check (re.match({invalid pattern}, string)) each key first (n) and then do `lambda varStr: re.sub('\W|^(?=\d)','_', varStr)`, that's n+n = 2n => O(n)
2. do `lambda varStr: re.sub('\W|^(?=\d)','_', varStr)` without checking, then that's n => O(n)

I think 2. is better?

**Comment by BoPeng** [comment] 2018-05-23 20:15
I agree with you because checking non-alphabetic characters in the name is not trivial so we might as well do the checking and fixing all at once.

Note that you do not have to use a lambda function here because a lambda function will be created each time so technically speaking slower than a pre-defined function.

**Comment by BoPeng** [comment] 2018-05-23 20:18
Note that you can also pre-compile the regular expression. Check the `re` module for details.

**Comment by HenryLeongStat** [comment] 2018-05-23 20:20
>Note that you do not have to use a lambda function here because a lambda function will be created each time so technically speaking slower than a pre-defined function.

I see! I thought lambda function is better because we might not want to create a function, which will use a "name" and increase the probability of the user to have "naming conflict". Let me think a more complicated name.

>Note that you can also pre-compile the regular expression. Check the re module for details.

I see! If using `re.sub('\W|^(?=\d)','_', varStr)`, the regular expression will compile every-time. I have been using `re` a lot combining with `BeautifulSoup` a lot lately, but still having a hard time to use `re`.

**Comment by HenryLeongStat** [comment] 2018-05-23 20:55
Still fail since `_` cannot be the beginning of the key of R list
```
> list(_11=1)
Error: unexpected input in "list(_"
```

**Comment by HenryLeongStat** [comment] 2018-05-23 20:56
Maybe `re.sub('\W|^(?=\d)','sos_', varStr)`?

**Comment by BoPeng** [comment] 2018-05-23 20:56
Then change everything to `.`?

**Comment by HenryLeongStat** [comment] 2018-05-23 20:57
Still fail
```
> list(.11=1)
Error: unexpected '=' in "list(.11="
```

**Comment by BoPeng** [comment] 2018-05-23 20:58
`.11` is a float number. :smile:

**Comment by HenryLeongStat** [comment] 2018-05-23 21:00
😅 right... 

Corrected my 2 previous comment, not `re.sub('\W|^(?=\d)','sos_', varStr)` but if the beginning of the key string is `_` (after we do `re.sub('\W|^(?=\d)','_', varStr)`), then we can add `sos` in the beginning.

**Comment by BoPeng** [comment] 2018-05-23 21:01
I think you should follow the convention of R's [make.names](http://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html).

**Comment by HenryLeongStat** [comment] 2018-05-23 21:06
So cool that there is a function like that!

However, it doesn't seem to work inside `list()`, and that's kinda weird...
```
> list(make.names(.11)=1)
Error: unexpected '=' in "list(make.names(.11)="
> make.names(.11)
[1] "X0.11"
> list(make.names(_11)=1)
Error: unexpected input in "list(make.names(_"
> make.names(_11)
Error: unexpected input in "make.names(_"
> make.names("_11")
[1] "X_11"
```

**Comment by BoPeng** [comment] 2018-05-23 21:08
I think you can define your own version of `make.names` in python to avoid the trouble of quoting a string, because the name itself might contain quote marks and will mess up the entire expression.

**Comment by BoPeng** [comment] 2018-05-23 21:10
Something like:
```
def make_name(obj):
    name = str(obj)
    if name.isalpha():
        return name
    if not name[0].isalpha:
        name = 'x' + name
    return re.sub(....)
```

**Comment by HenryLeongStat** [comment] 2018-05-23 21:18
That's cool! Basically `.isalpha()` = `if re.match[A-Za-z]` (I guess), but it should be faster than `re`!

**Comment by HenryLeongStat** [comment] 2018-05-23 21:57
It should be working now. I will add the test case.

Should we update the documentation?

**Comment by HenryLeongStat** [comment] 2018-05-24 02:37
It is weird... The test passes on my machine.

```
$ python test_R_kernel.py
/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
./Users/manchongleong/anaconda/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
....
----------------------------------------------------------------------
Ran 5 tests in 7.767s

OK
```

**Comment by BoPeng** [comment] 2018-05-24 02:38
As long as it passes, it should be fine.

**Comment by HenryLeongStat** [comment] 2018-05-24 02:38
OK! Then it should be ready to merge!

**Comment by BoPeng** [comment] 2018-05-24 02:40
I commented on your code.

**Comment by HenryLeongStat** [comment] 2018-05-24 03:32
Hmm.. I couldn't see it yet...

**Comment by BoPeng** [comment] 2018-05-24 03:36
From https://github.com/vatlab/sos-r/pull/7/files ?

**Comment by HenryLeongStat** [comment] 2018-05-24 03:57
Weird... I don't see any comment...

<img width="1261" alt="screen shot 2018-05-23 at 10 56 32 pm" src="https://user-images.githubusercontent.com/26916551/40463760-98465c5e-5edc-11e8-8053-0c9315745296.png">

**Comment by BoPeng** [comment] 2018-05-24 04:02
![image](https://user-images.githubusercontent.com/9889312/40463872-560b8570-5edd-11e8-88e6-8f65098847b9.png)

**Comment by HenryLeongStat** [comment] 2018-05-24 04:08
Still can't see it! GitHub's bug!?

**Comment by HenryLeongStat** [comment] 2018-05-24 04:19
So the compile in the global namespace should have the special name?

**Comment by BoPeng** [comment] 2018-05-24 21:38
check your code again and see if you can make it shorter.

**Comment by HenryLeongStat** [comment] 2018-05-24 21:45
Thinking... 

Professor, is
```
if condition1:
    func1
if condition2:
    func1
```

performing the same as:
```
if condition1 or condition2:
    func1
```
??

**Comment by BoPeng** [comment] 2018-05-24 21:47
yeah... do not have to ask me this.. try it on a python shell would suffice.

**Comment by HenryLeongStat** [comment] 2018-05-24 21:56
Checking the efficiency of the py code, simply use something like
```
import time
t0 = time.time()
xxxxxx
t1 = time.time()
print(t1-t0)
```
?

Seems not that elegant...

**Comment by HenryLeongStat** [comment] 2018-05-24 22:00
```
def make_name(name):
    if name.isalpha():
        return name
    # the best way to detect an empty string is `if not {string}`
    if not name[0].isalpha() or name:
        name = 'X' + name
    return re.sub('\W', '_', name)
```

This one is shorter, but I thing would perform worse? Because it needs to do `name = 'X' + name` and `re.sub('\W', '_', name)` even though the input is `''`

**Comment by BoPeng** [comment] 2018-05-24 22:08
Your program would crash with `name=''`....

**Comment by HenryLeongStat** [comment] 2018-05-24 22:12
Oh I see... It should be 
```
def make_name(name):
    if name.isalpha():
        return name
    # the best way to detect an empty string is `if not {string}`
    if not name or name[0].isalpha():
        name = 'X' + name
    return re.sub('\W', '_', name)
```

But I still think
```
def make_name(name):
    if name.isalpha():
        return name
    # the best way to detect an empty string is `if not {string}`
    if not name:
        return 'X'
    if not name[0].isalpha():
        name = 'X' + name
    return re.sub('\W', '_', name)
```

performs slightly better? However, definitely the upper one is shorter. The below one is a little bit redundant...

**Comment by BoPeng** [comment] 2018-05-24 22:17
You are considering the wrong thing here.

> if not name or name[0].isalpha():

is a sanity check to prevent a crash in a rare case. It is definitely needed so performance is not an issue here. Then adding a separate `if` logic for a rare case is a waste.

You should get use of checking your code over (and over), thinking of all corner cases, thinking of shorter ways, thinking of performance improvement, etc... Making it "work" is only the first step.

**Comment by HenryLeongStat** [comment] 2018-05-24 22:27
Understood! Bad things and habits for using IDE (for me) is that it sometimes saves the functions or vars, and I forget to renew the function... Should give up using IDE or be more cautious about it... 

But I enjoy thinking about the performance issue like it! And sometimes it is like a trade-off for shorter code or better performance... For this case, I think I overthought it because even thought a crazy case like:
```
{'' : {a: {'' : {b: {'' : .....}}}}}
```

it won't boost the speed a lot and make the code looks bad... 😢

**Comment by BoPeng** [comment] 2018-05-24 22:31
You have a logic error in your code. Let us see if the tests pass this time.

You should run the tests in a notebook before you commit though.

**Comment by HenryLeongStat** [comment] 2018-05-24 22:39
My bad.... I did use the dataset to check it, but forget the corner case... 😓

**Comment by BoPeng** [comment] 2018-05-25 04:40
Test fixed.

Note that we are testing for dictionaries so the order of keys is not guaranteed.

**Closed by BoPeng** 2018-05-25 04:40 UTC
Labels: bug

**Comment by HenryLeongStat** [comment] 2018-05-25 14:39
Oh! I thought that the new python's Dict is ordered...

**Comment by BoPeng** [comment] 2018-05-25 14:42
But that is an "implementation detail" and is not guaranteed. Anyway, the test has passed and I have made a new release of sos-r.

**Comment by HenryLeongStat** [comment] 2018-05-25 14:45
Next one is the Recursive var!!! 💪🏻
